name: Push LeetCode Solutions to GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight

jobs:
  push_solutions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "ogbeidemurphy@gmail.com"
          git config --global user.name "Murphy Ogbeide"

      - name: Add LeetCode solutions to repo
        run: |
          # Copy your local LeetCode solutions to the correct directory
          # Ensure that solutions are in 'leetcode_solutions/' directory
          cp -r /path/to/your/local/solutions/* leetcode_solutions/

          # Stage, commit, and push changes
          git add leetcode_solutions/*
          git commit -m "Add new LeetCode solutions"
          git push origin main
